apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  type: NodePort
  selector:
    app: webook-mysql
  ports:
    - protocol: TCP
      name: mysql
      port: 3308
      targetPort: 3306
      nodePort: 30001
