apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
  labels:
    app: webook-mysql-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # 1GB
      storage: 1Gi

